---

- name: Add standard repos
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    line: "{{ item }}"
    state: present
    create: yes
  loop:
    - "deb http://archive.ubuntu.com/ubuntu noble main restricted universe multiverse"
    - "deb http://archive.ubuntu.com/ubuntu noble-updates main restricted universe multiverse"
    - "deb http://archive.ubuntu.com/ubuntu noble-backports main restricted universe multiverse"
    - "deb http://security.ubuntu.com/ubuntu noble-security main restricted universe multiverse"

- name: Update apt cache
  apt:
    update_cache: yes
