---

- name: Install dependencies
  apt:
    name: build-essential
    state: present
  when: ansible_os_family == 'Debian'

- name: Create 3proxy user
  user:
    name: 3proxy
    shell: /usr/sbin/nologin
    system: yes

- name: Download 3proxy source
  get_url:
    url: "https://github.com/z3APA3A/3proxy/archive/refs/tags/0.9.5.tar.gz"
    dest: /tmp/3proxy.tar.gz

- name: Extract 3proxy source
  unarchive:
    src: /tmp/3proxy.tar.gz
    dest: /usr/local/src/
    remote_src: yes

- name: Link Linux Makefile in repo root
  file:
    src: /usr/local/src/3proxy-0.9.5/Makefile.Linux
    dest: /usr/local/src/3proxy-0.9.5/src/Makefile
    state: link
    force: yes

- name: Build 3proxy
  make:
    chdir: '/usr/local/src/3proxy-0.9.5/src'

- name: Copy binary
  copy:
    src: /usr/local/src/3proxy-0.9.5/bin/3proxy
    dest: /usr/local/bin/3proxy
    mode: '0755'
    remote_src: yes

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: 3proxy
    group: 3proxy
    mode: '0755'
  loop:
    - /etc/3proxy
    - /var/log/3proxy
